# Generated by Django 6.0.5 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('miejsce', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=100)),
                ('organizator', models.CharField(max_length=200)),
                ('opis', models.TextField()),
            ],
        ),
    ]
