# Generated by Django 6.0.5 on 2026-06-03 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydarzenia', '0002_wydarzenie_autor_alter_wydarzenie_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wydarzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisy', to='wydarzenia.wydarzenie')),
            ],
            options={
                'unique_together': {('wydarzenie', 'uzytkownik')},
            },
        ),
    ]
